import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Provider } from "@/providers/thirdwebProvider";
import SideBar from "./_components/SideBar";

const bricolage = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bricolage.className}>
        <Provider>
          <div className="flex w-full h-screen py-4">
            <SideBar />
            <div className="rounded-2xl flex-1 w-full">
              <div className="w-[98%] h-full overflow-auto py-4 bg-[#18181B] rounded-2xl">
                {children}
              </div>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
